### PR TITLE
feat: Initial repo setup

### PR DESCRIPTION
**Pull request by frgfm**
This PR aims at settings the python project by:
- adding an empty python project folder
- adding python package setup script
- adding sphinx automatic documentation files
- adding a template unittest (for version formatting)
- setting up CI jobs for unittesting, doc building and lint checking

Any feedback is welcome!

### CODE REVIEW

**Comment by fe51** [comment]
Hey @frgfm , thank you for this setup PR ! Sounds pretty good to me.

**Review by fe51 — APPROVED** [review]

**Review by chloeskt — APPROVED** [review]
RAS

**Review by vdwow — APPROVED** [review]

**Review by dataJSA — APPROVED** [review]
Thanks for the setup @frgfm everything seems to be fine !

**Comment by frgfm** [comment]
Documentation will be available over there after each merge into master: https://pyronear.github.io/pyronear-datascience/

**Pull request merged**
